services:
  - type: web
    name: octopus
    runtime: go
    buildCommand: "bash build.sh"
    startCommand: "./app start"
    envVars:
      - key: OCTOPUS_SERVER_HOST
        value: 0.0.0.0
      - key: OCTOPUS_SERVER_PORT
        value: 8080
      # Option 1: SQLite (đơn giản, không lo network transfer)
      - key: OCTOPUS_DATABASE_TYPE
        value: sqlite
      - key: OCTOPUS_DATABASE_PATH
        value: /opt/render/project/.render/data.db

      # Option 2: PostgreSQL (comment option 1, uncomment dưới)
      # - key: OCTOPUS_DATABASE_TYPE
      #   value: postgres
      # - key: OCTOPUS_DATABASE_PATH
      #   value: "postgresql://[USER]:[PASSWORD]@[HOST]:5432/postgres?sslmode=require"